In [2]:
import numpy as np

TALLER 1

LINA ROCIO CARDENAS FERNANDEZ 

GRUPO 2

1.	Tienen el siguiente arreglo : 

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Como es posible obtener el siguiente resultado:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [3]:
#RESPUESTA
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
arr[[1,3,5,7,9]]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


2.	Tienen el siguiente input:

np.arange(10)

Como se puede hacer para obtener el siguiente resultado:

#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9]])




In [10]:
#RESPUESTA
a=np.arange(10)
print(a)
print('opcion 1')
b=a.reshape((2,5))
print(b)
print('-------------------------')
print('opcion 2')
a.shape=[2,5]
print(a)

[0 1 2 3 4 5 6 7 8 9]
opcion 1
[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------------------
opcion 2
[[0 1 2 3 4]
 [5 6 7 8 9]]


3.	Con base en el siguiente input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Obtener el siguiente resultado
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])



In [12]:
#RESPUESTA
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print('----------------')
print(b)


[[0 1 2 3 4]
 [5 6 7 8 9]]
----------------
[[1 1 1 1 1]
 [1 1 1 1 1]]


4.	Con base en el siguiente input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Obtener el siguiente output

array([2, 4])


In [23]:
#RESPUESTA
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)
print('-------------------------')
#opcion 1
array=(a[1],b[5])
print(array)
#opcion 2
array=(a[-7],b[-3])
print(array)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
-------------------------
(2, 4)
(2, 4)


5.	Del siguiente input:

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Obtener el siguiente output

array([1,2,3,4])


In [28]:
#RESPUESTA
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a)
print(b)
print('-------------------------')
#opcion 1
array=(a[[0,1,2,3]])
print(array)
#opcion 2
array=(a[[ -5,-4,-3,-2]])
print(array)


[1 2 3 4 5]
[5 6 7 8 9]
-------------------------
[1 2 3 4]
[1 2 3 4]


6.	Con el siguiente input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Obtener:

(array([6, 9, 10]),)


In [35]:
#REPUESTA
a = np.array([2, 6, 1, 9, 10, 3, 27])
print (a)
print('opcion 1')
array=(a[[ 1,3,4]])
print (array)
print('opcion 2')
array=(a[[ -6,-4,-3]])
print (array)

[ 2  6  1  9 10  3 27]
opcion 1
[ 6  9 10]
opcion 2
[ 6  9 10]



7.	Invertir las filas de un arreglo de matriz 2D

arr = np.arange(9).reshape(3,3)

Output deseado:

array([[6, 7, 8],

       [3, 4, 5],

       [0, 1, 2]])
       




In [45]:
#RESPUESTA
arr = np.arange(9).reshape(3,3)
print(arr)
print('------')
arrayb =np.array ([[6,6,6],[0,0,0],[-6,-6,-6]])
print(arrayb)
print('------')
array=arr+arrayb
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------
[[ 6  6  6]
 [ 0  0  0]
 [-6 -6 -6]]
------
[[6 7 8]
 [3 4 5]
 [0 1 2]]
